### ISSUE TITLE
Module doesn't show.

### ISSUE THREAD

**Issue by jacksonhardaway** [samerton/Nameless-Nextyle-Updated#4]
I've installed the module onto a Nameless site, but the customization area for the template / module never appears in the StaffCP. Any help?

**Comment by samerton** [comment]
Once the module is installed and activated (StaffCP -> Modules), there should be a link in the sidebar near the bottom for Nextyle.

Initially, this will only show if you are in the group with ID 2 (StaffCP -> Groups, the Group ID is listed down the left hand side), and if you are in a different group you will have to customise the permissions to give yourself access.

**Comment by jacksonhardaway** [comment]
Okay, good to know. Thanks!
